Repository Green-Software-Foundation/if-plugins, pull requests merged in 2023-12, with the labels that each got.

#12 Cloud Instance Metadata Model - Add Instance Data & Fix issues in Azure Instance Type handling
  src/__tests__/unit/lib/cloud-instance-metadata/index.test.ts
  src/lib/cloud-instance-metadata/aws-instances.json
  src/lib/cloud-instance-metadata/azure-instances.json
  src/lib/cloud-instance-metadata/index.ts
Labels: enhancement

#13 Sync issue templates with IF repo
  .github/ISSUE_TEMPLATE/agenda.md
  .github/ISSUE_TEMPLATE/dev-ticket.md
  .github/ISSUE_TEMPLATE/model-plugin.md
Labels: project-management

#15 Unit test improvements
  .gitignore
  package.json
  src/__tests__/unit/lib/cloud-instance-metadata/index.test.ts
  src/__tests__/unit/lib/e-mem/index.test.ts
  src/__tests__/unit/lib/sci-e/index.test.ts
  src/__tests__/unit/lib/sci-m/index.test.ts
  src/__tests__/unit/lib/sci-o/index.test.ts
  src/__tests__/unit/lib/sci/index.test.ts
  src/__tests__/unit/lib/shell/index.test.ts
  src/__tests__/unit/lib/tdp-finder/index.test.ts
  src/lib/cloud-instance-metadata/index.ts
  src/lib/e-mem/index.ts
  src/lib/sci-e/index.ts
  src/lib/sci-m/index.ts
  src/lib/sci-o/index.ts
  src/lib/sci/index.ts
  src/lib/shell/index.ts
  src/lib/tdp-finder/index.ts
Labels: tests, medium-priority, size: medium
