Repository Green-Software-Foundation/if-plugins, pull requests merged in 2024-05, with the labels that each got.

#90 feat(src): subtract plugin
  README.md
  src/__tests__/unit/lib/subtract/index.test.ts
  src/lib/index.ts
  src/lib/subtract/README.md
  src/lib/subtract/index.ts
  src/lib/subtract/types.ts
Labels: awaiting-qa

#94 Lint staged
  .lintstagedrc.js
  package-lock.json
  package.json
Labels: feature

#91 feat(src): generic exponent plugin
  README.md
  src/__tests__/unit/lib/exponent/index.test.ts
  src/lib/exponent/README.md
  src/lib/exponent/index.ts
  src/lib/exponent/types.ts
  src/lib/index.ts
Labels: awaiting-qa

#92 Fix `shell` plugin outputs
  src/lib/shell/index.ts
Labels: size: small, awaiting-dev-review, fix
