Repository Green-Software-Foundation/if-plugins, pull requests merged in 2024-04, with the labels that each got.

#62 Fix e-net and e-mem plugins
  package-lock.json
  src/__tests__/unit/lib/e-mem/index.test.ts
  src/__tests__/unit/lib/e-net/index.test.ts
  src/lib/e-mem/README.md
  src/lib/e-mem/index.ts
  src/lib/e-net/README.md
  src/lib/e-net/index.ts
Labels: bug, medium-priority, size: small, awaiting-qa

#64 Fix defaults and inputs merging bug in mock-observations
  src/lib/mock-observations/index.ts
Labels: size: small, dev-review-pass, awaiting-qa, fix

#67 Update readme for cloud metadata plugin
  src/lib/cloud-metadata/README.md
Labels: documentation, medium-priority, size: small, awaiting-dev-review, fix

#68 fix randint validation in mock-observations plugin
  src/__tests__/unit/lib/mock-observations/index.test.ts
  src/lib/mock-observations/helpers/rand-int-generator.ts
Labels: bug, size: small, awaiting-dev-review

#71 Update caiso_north geolocation
  src/lib/cloud-metadata/gsf-data.csv
Labels: size: small, dev-review-pass, awaiting-qa, fix

#72 Add `outputs` parameter into readme files manifest examples
  src/lib/coefficient/README.md
  src/lib/csv-export/README.md
  src/lib/divide/README.md
  src/lib/e-mem/README.md
  src/lib/e-net/README.md
  src/lib/multiply/README.md
  src/lib/regex/README.md
  src/lib/sci-e/README.md
  src/lib/sci-m/README.md
  src/lib/sci-o/README.md
  src/lib/sci/README.md
  src/lib/shell/README.md
  src/lib/sum/README.md
  src/lib/tdp-finder/README.md
Labels: bug, size: medium, awaiting-dev-review

#73 chore(package): release v0.3.1 ✨
  package-lock.json
  package.json
Labels: release

#76 Release v0.3.2
  package-lock.json
  package.json
Labels: release

#77 Update cloud-metadata readme file
  src/lib/cloud-metadata/README.md
  src/lib/shell/README.md
  src/lib/tdp-finder/README.md
Labels: size: small, dev-review-pass, awaiting-qa, fix

#79 remove cpu/utilization for clarity
  src/lib/cloud-metadata/README.md
Labels: medium-priority, size: small, fix

#84 Update issue templates in if-plugins
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feedback.md
  .github/ISSUE_TEMPLATE/model-plugin.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: project-management
